CREATE TABLE IF NOT EXISTS public.attendance_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    employee_id BIGINT NOT NULL,
    date DATE NOT NULL,
    time_in TIMESTAMP WITH TIME ZONE NOT NULL,
    time_out TIMESTAMP WITH TIME ZONE,
    duration INTEGER,
    notes TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    check_in_method VARCHAR(50) NOT NULL, -- 'manual', 'nfc'
    location VARCHAR(255),
    reader_id VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    metadata JSONB
);

-- Foreign key constraints (adjust exact names based on your DB schema if they differ, but standard approach)
ALTER TABLE public.attendance_requests
    ADD CONSTRAINT fk_attendance_requests_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE public.attendance_requests ENABLE ROW LEVEL SECURITY;

-- Optional: Create basic policies so that users can read their own requests and admins can see all.
-- This follows standard Supabase security patterns.
CREATE POLICY "Users can view their own requests based on employee relation"
    ON public.attendance_requests FOR SELECT
    USING (
        employee_id IN (
            SELECT id FROM public.employees 
            WHERE user_id = auth.uid() 
            AND tenant_id = attendance_requests.tenant_id
        )
    );

CREATE POLICY "Admins can view and update all requests"
    ON public.attendance_requests FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE id = auth.uid() 
            AND role IN ('Admin', 'SuperAdmin', 'Manager') 
            AND tenant_id = attendance_requests.tenant_id
        )
    );
