-- Leave Policies table: stores configurable leave entitlement rules per tenant
-- Admin can update these values at any time to adjust leave rules

create table if not exists public.leave_policies (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  leave_type text not null, -- annual, sick, family, study, maternity, paternity, unpaid
  
  -- Tenure-based annual entitlement (only used when leave_type = 'annual')
  tenure_0_2_days numeric(6,2) not null default 12,    -- 0-2 years: 12 days/year
  tenure_2_5_days numeric(6,2) not null default 18,    -- 2-5 years: 18 days/year
  tenure_5_10_days numeric(6,2) not null default 20,   -- 5-10 years: 20 days/year
  tenure_10_plus_days numeric(6,2) not null default 23, -- 10+ years: 23 days/year
  
  -- Fixed entitlement (for non-annual types)
  fixed_days_per_year numeric(6,2) not null default 0,
  
  -- Carry forward rules
  max_carry_forward numeric(6,2) not null default 0,
  
  -- Whether this leave type requires document upload
  requires_document boolean not null default false,
  
  -- Whether interns are eligible
  intern_eligible boolean not null default false,
  
  -- Display order
  display_order integer not null default 0,
  
  -- Whether this leave type is active
  is_active boolean not null default true,
  
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  unique (tenant_id, leave_type)
);

alter table public.leave_policies enable row level security;

-- Also add attachment_url column to leave_requests for document uploads
alter table public.leave_requests 
  add column if not exists attachment_url text,
  add column if not exists attachment_name text;
